
import { Application, Personnel, Department, Equipment, Attachment } from '@/types';

const generateId = () => Math.random().toString(36).substring(2, 9);

export const mockApplications: Application[] = [
  {
    id: 'app-001',
    type: 'setup',
    status: 'reviewing',
    currentStep: 7,
    basicInfo: {
      orgName: '北京康泰门诊部',
      orgCategory: 'outpatient',
      businessNature: '营利性',
      legalRepresentative: '张三',
      legalIdCard: '110101198001011234',
      legalPhone: '13800138001',
      mainDirector: '李四',
      directorIdCard: '110102197505054321',
      directorPhone: '13900139002',
      practiceAddress: '北京市朝阳区建国路88号SOHO现代城A座1层',
      contactPhone: '010-88888888',
      registeredCapital: '500万元',
      businessScope: '内科、外科、妇科、医学检验科、医学影像科',
    },
    departments: [
      { id: generateId(), code: '03', name: '内科', level: '一级科目', remark: '常见病诊治' },
      { id: generateId(), code: '04', name: '外科', level: '一级科目', remark: '普通外科' },
      { id: generateId(), code: '05', name: '妇产科', level: '一级科目', remark: '妇科专业' },
    ],
    personnel: [
      {
        id: generateId(),
        name: '王医生',
        gender: '男',
        idCard: '110101197803031234',
        position: '执业医师',
        title: '主治医师',
        certificateNo: '110101197803031234',
        certificateValidDate: '2028-12-31',
        practiceScope: '内科专业',
      },
      {
        id: generateId(),
        name: '赵医生',
        gender: '女',
        idCard: '110102198006065678',
        position: '执业医师',
        title: '副主任医师',
        certificateNo: '110102198006065678',
        certificateValidDate: '2027-06-30',
        practiceScope: '外科专业',
      },
    ],
    premises: {
      buildingArea: '800',
      useArea: '650',
      houseNature: '商业用房',
      propertyProof: '房屋所有权证',
      layoutDescription: '一层为门诊大厅、内科、外科，二层为妇科、检验科、影像科',
      floors: '2层',
    },
    equipment: [
      { id: generateId(), name: '全自动生化分析仪', model: 'BS-380', quantity: 1, manufacturer: '迈瑞', purchaseDate: '2024-01-15' },
      { id: generateId(), name: '彩色B超诊断仪', model: 'DC-70', quantity: 1, manufacturer: '迈瑞', purchaseDate: '2024-02-20' },
      { id: generateId(), name: '心电图机', model: 'ECG-1200', quantity: 2, manufacturer: '光电', purchaseDate: '2024-01-10' },
    ],
    attachments: [
      { id: generateId(), category: '身份证明', fileName: '法人身份证.pdf', fileSize: 1024000, uploadTime: '2025-01-15 10:30', status: 'uploaded' },
      { id: generateId(), category: '资质证明', fileName: '医师资格证.pdf', fileSize: 2048000, uploadTime: '2025-01-15 11:00', status: 'uploaded' },
      { id: generateId(), category: '产权证明', fileName: '房产证.pdf', fileSize: 3072000, uploadTime: '2025-01-15 14:20', status: 'uploaded' },
      { id: generateId(), category: '平面图', fileName: '平面布局图.pdf', fileSize: 512000, uploadTime: '2025-01-15 15:00', status: 'uploaded' },
    ],
    promise: {
      hasLegalPerson: true,
      hasBusinessScope: true,
      hasQualifiedPersonnel: true,
      hasQualifiedPremises: true,
      hasQualifiedEquipment: true,
      hasAllAttachments: true,
      isTruthful: true,
    },
    versions: [
      { version: 'V1.0', submitTime: '2025-01-16 09:00', status: 'submitted', remark: '首次提交' },
    ],
    correctionOpinions: [],
    auditRecords: [],
    createdAt: '2025-01-10 09:00',
    submittedAt: '2025-01-16 09:00',
  },
  {
    id: 'app-002',
    type: 'setup',
    status: 'returned',
    currentStep: 7,
    basicInfo: {
      orgName: '上海仁爱诊所',
      orgCategory: 'clinic',
      businessNature: '营利性',
      legalRepresentative: '王五',
      legalIdCard: '310101197512121234',
      legalPhone: '13600136003',
      mainDirector: '王五',
      directorIdCard: '310101197512121234',
      directorPhone: '13600136003',
      practiceAddress: '上海市浦东新区张江高科技园区碧波路666号',
      contactPhone: '021-66666666',
      registeredCapital: '100万元',
      businessScope: '内科、中医科',
    },
    departments: [
      { id: generateId(), code: '03', name: '内科', level: '一级科目', remark: '' },
      { id: generateId(), code: '23', name: '中医科', level: '一级科目', remark: '针灸、推拿' },
    ],
    personnel: [
      {
        id: generateId(),
        name: '陈医生',
        gender: '男',
        idCard: '310101198001011234',
        position: '执业医师',
        title: '主治医师',
        certificateNo: '310101198001011234',
        certificateValidDate: '2026-06-30',
        practiceScope: '内科专业',
      },
    ],
    premises: {
      buildingArea: '200',
      useArea: '180',
      houseNature: '商业用房',
      propertyProof: '租赁合同',
      layoutDescription: '诊室2间，治疗室1间，观察室1间，药房1间',
      floors: '1层',
    },
    equipment: [
      { id: generateId(), name: '血压计', model: 'HEM-7136', quantity: 3, manufacturer: '欧姆龙', purchaseDate: '2024-03-01' },
      { id: generateId(), name: '听诊器', model: 'Littmann', quantity: 2, manufacturer: '3M', purchaseDate: '2024-03-01' },
    ],
    attachments: [
      { id: generateId(), category: '身份证明', fileName: '法人身份证.pdf', fileSize: 1024000, uploadTime: '2025-02-01 10:00', status: 'uploaded' },
      { id: generateId(), category: '资质证明', fileName: '医师资格证.pdf', fileSize: 2048000, uploadTime: '2025-02-01 10:30', status: 'uploaded' },
      { id: generateId(), category: '产权证明', fileName: '租赁合同.pdf', fileSize: 1536000, uploadTime: '2025-02-01 11:00', status: 'uploaded' },
      { id: generateId(), category: '平面图', fileName: '', fileSize: 0, uploadTime: '', status: 'pending' },
    ],
    promise: {
      hasLegalPerson: true,
      hasBusinessScope: true,
      hasQualifiedPersonnel: true,
      hasQualifiedPremises: true,
      hasQualifiedEquipment: true,
      hasAllAttachments: false,
      isTruthful: true,
    },
    versions: [
      { version: 'V1.0', submitTime: '2025-02-05 14:00', status: 'submitted', remark: '首次提交' },
      { version: 'V1.1', submitTime: '2025-02-10 16:30', status: 'returned', remark: '材料补正' },
    ],
    correctionOpinions: [
      { id: generateId(), content: '缺少平面布局图，请补充上传。', date: '2025-02-08', operator: '审核员A' },
      { id: generateId(), content: '医师执业范围与诊疗科目不完全匹配，请确认。', date: '2025-02-08', operator: '审核员A' },
    ],
    auditRecords: [
      { id: generateId(), version: 'V1.0', action: 'submit', actionLabel: '提交申报', operator: '办证专员', time: '2025-02-05 14:00', opinions: ['首次提交设立登记申报材料'], status: 'submitted' },
      { id: generateId(), version: 'V1.0', action: 'accept', actionLabel: '受理材料', operator: '受理员B', time: '2025-02-05 15:30', opinions: ['材料齐全，予以受理'], status: 'reviewing' },
      { id: generateId(), version: 'V1.0', action: 'review', actionLabel: '进入审核', operator: '审核员A', time: '2025-02-06 09:00', opinions: ['开始审核申报材料'], status: 'reviewing' },
      { id: generateId(), version: 'V1.0', action: 'return', actionLabel: '退回补正', operator: '审核员A', time: '2025-02-08 10:30', opinions: ['缺少平面布局图，请补充上传。', '医师执业范围与诊疗科目不完全匹配，请确认。'], status: 'returned' },
      { id: generateId(), version: 'V1.1', action: 'submit', actionLabel: '补正提交', operator: '办证专员', time: '2025-02-10 16:30', opinions: ['根据补正意见补充了相关材料'], status: 'submitted' },
    ],
    createdAt: '2025-01-20 10:00',
    submittedAt: '2025-02-05 14:00',
  },
  {
    id: 'app-003',
    type: 'change',
    status: 'approved',
    currentStep: 7,
    basicInfo: {
      orgName: '广州康护护理站',
      orgCategory: 'nursing_station',
      businessNature: '非营利性',
      legalRepresentative: '孙六',
      legalIdCard: '440101197010101234',
      legalPhone: '13700137004',
      mainDirector: '周七',
      directorIdCard: '440102198202024321',
      directorPhone: '13500135005',
      practiceAddress: '广州市天河区天河路385号太古汇一座15层',
      contactPhone: '020-77777777',
      registeredCapital: '50万元',
      businessScope: '社区护理、康复护理、老年护理',
    },
    departments: [],
    personnel: [
      {
        id: generateId(),
        name: '李护士',
        gender: '女',
        idCard: '440103198808081234',
        position: '护士',
        title: '护师',
        certificateNo: '440103198808081234',
        certificateValidDate: '2029-08-08',
        practiceScope: '护理专业',
      },
      {
        id: generateId(),
        name: '张护士',
        gender: '女',
        idCard: '440104199009095678',
        position: '护士',
        title: '护士',
        certificateNo: '440104199009095678',
        certificateValidDate: '2028-09-09',
        practiceScope: '护理专业',
      },
    ],
    premises: {
      buildingArea: '300',
      useArea: '260',
      houseNature: '商业用房',
      propertyProof: '租赁合同',
      layoutDescription: '护理站大厅、治疗室、观察室、康复室、办公室',
      floors: '1层',
    },
    equipment: [
      { id: generateId(), name: '护理床', model: 'A-100', quantity: 5, manufacturer: '鱼跃', purchaseDate: '2024-06-01' },
      { id: generateId(), name: '制氧机', model: '5L', quantity: 3, manufacturer: '鱼跃', purchaseDate: '2024-06-01' },
      { id: generateId(), name: '雾化器', model: '403T', quantity: 4, manufacturer: '鱼跃', purchaseDate: '2024-06-01' },
    ],
    attachments: [
      { id: generateId(), category: '身份证明', fileName: '法人身份证.pdf', fileSize: 1024000, uploadTime: '2025-03-01 09:00', status: 'uploaded' },
      { id: generateId(), category: '资质证明', fileName: '护士资格证.pdf', fileSize: 2048000, uploadTime: '2025-03-01 09:30', status: 'uploaded' },
      { id: generateId(), category: '产权证明', fileName: '租赁合同.pdf', fileSize: 1536000, uploadTime: '2025-03-01 10:00', status: 'uploaded' },
      { id: generateId(), category: '平面图', fileName: '平面布局图.pdf', fileSize: 512000, uploadTime: '2025-03-01 10:30', status: 'uploaded' },
      { id: generateId(), category: '设备清单', fileName: '设备清单.pdf', fileSize: 768000, uploadTime: '2025-03-01 11:00', status: 'uploaded' },
    ],
    promise: {
      hasLegalPerson: true,
      hasBusinessScope: true,
      hasQualifiedPersonnel: true,
      hasQualifiedPremises: true,
      hasQualifiedEquipment: true,
      hasAllAttachments: true,
      isTruthful: true,
    },
    versions: [
      { version: 'V1.0', submitTime: '2025-03-05 10:00', status: 'submitted', remark: '首次提交' },
      { version: 'V1.1', submitTime: '2025-03-10 14:00', status: 'approved', remark: '变更通过' },
    ],
    correctionOpinions: [
      { id: generateId(), content: '变更申请材料齐全，同意通过。', date: '2025-03-12', operator: '审核员B' },
    ],
    auditRecords: [
      { id: generateId(), version: 'V1.0', action: 'submit', actionLabel: '提交申报', operator: '办证专员', time: '2025-03-05 10:00', opinions: ['首次提交变更登记申报材料'], status: 'submitted' },
      { id: generateId(), version: 'V1.0', action: 'accept', actionLabel: '受理材料', operator: '受理员B', time: '2025-03-05 11:00', opinions: ['材料齐全，予以受理'], status: 'reviewing' },
      { id: generateId(), version: 'V1.0', action: 'review', actionLabel: '进入审核', operator: '审核员B', time: '2025-03-06 10:00', opinions: ['开始审核申报材料'], status: 'reviewing' },
      { id: generateId(), version: 'V1.0', action: 'approve', actionLabel: '审核通过', operator: '审核员B', time: '2025-03-08 14:00', opinions: ['变更申请材料齐全，同意通过。'], status: 'approved' },
    ],
    createdAt: '2025-02-25 10:00',
    submittedAt: '2025-03-05 10:00',
  },
  {
    id: 'app-004',
    type: 'setup',
    status: 'draft',
    currentStep: 3,
    basicInfo: {
      orgName: '深圳康健诊所',
      orgCategory: 'clinic',
      businessNature: '营利性',
      legalRepresentative: '',
      legalIdCard: '',
      legalPhone: '',
      mainDirector: '',
      directorIdCard: '',
      directorPhone: '',
      practiceAddress: '',
      contactPhone: '',
      registeredCapital: '',
      businessScope: '',
    },
    departments: [],
    personnel: [],
    premises: {
      buildingArea: '',
      useArea: '',
      houseNature: '',
      propertyProof: '',
      layoutDescription: '',
      floors: '',
    },
    equipment: [],
    attachments: [],
    promise: {
      hasLegalPerson: false,
      hasBusinessScope: false,
      hasQualifiedPersonnel: false,
      hasQualifiedPremises: false,
      hasQualifiedEquipment: false,
      hasAllAttachments: false,
      isTruthful: false,
    },
    versions: [],
    correctionOpinions: [],
    auditRecords: [],
    createdAt: '2025-06-10 15:00',
    submittedAt: '',
  },
  {
    id: 'app-005',
    type: 'setup',
    status: 'draft',
    currentStep: 5,
    basicInfo: {
      orgName: '杭州仁和门诊部',
      orgCategory: 'outpatient',
      businessNature: '营利性',
      legalRepresentative: '吴九',
      legalIdCard: '330101197507071234',
      legalPhone: '13900139006',
      mainDirector: '郑十',
      directorIdCard: '330102198011115678',
      directorPhone: '13800138007',
      practiceAddress: '杭州市西湖区文三路478号华星时代广场C座',
      contactPhone: '0571-88888888',
      registeredCapital: '300万元',
      businessScope: '内科、外科、儿科、医学检验科',
    },
    departments: [
      { id: generateId(), code: '03', name: '内科', level: '一级科目', remark: '' },
      { id: generateId(), code: '04', name: '外科', level: '一级科目', remark: '' },
      { id: generateId(), code: '06', name: '儿科', level: '一级科目', remark: '' },
    ],
    personnel: [
      {
        id: generateId(),
        name: '刘医生',
        gender: '男',
        idCard: '330103198205051234',
        position: '执业医师',
        title: '主治医师',
        certificateNo: '330103198205051234',
        certificateValidDate: '2027-05-05',
        practiceScope: '内科专业',
      },
    ],
    premises: {
      buildingArea: '500',
      useArea: '420',
      houseNature: '商业用房',
      propertyProof: '房屋所有权证',
      layoutDescription: '',
      floors: '2层',
    },
    equipment: [],
    attachments: [],
    promise: {
      hasLegalPerson: false,
      hasBusinessScope: false,
      hasQualifiedPersonnel: false,
      hasQualifiedPremises: false,
      hasQualifiedEquipment: false,
      hasAllAttachments: false,
      isTruthful: false,
    },
    versions: [],
    correctionOpinions: [],
    auditRecords: [],
    createdAt: '2025-05-20 09:00',
    submittedAt: '',
  },
];

export { generateId };
